### ISSUE TITLE
"reboot" does not reboot

### ISSUE THREAD

**Issue by jakajancar** [mist64/xhyve#38]
Doing a "sudo reboot" causes the app to exit, not reboot:

    The system is going down NOW!
    Sent SIGTERM to all processes
    Sent SIGKILL to all processes
    Requesting system reboot
    reboot: Restarting system
    reboot: machine restart

    $

**Comment by jbergstroem** [comment]
This isn't handled in bhyve either.

**Comment by xez** [comment]
This is expected. The current model in bhyve is to restart the process, rather than resetting the device state. `xhyve` will give you a different exit code depending on the shutdown event (`VM_SUSPEND_RESET`, `VM_SUSPEND_POWEROFF`, `VM_SUSPEND_TRIPLEFAULT`, ...).

This is typically handled by the run scripts. For example: http://people.freebsd.org/~neel/bhyve/vmrun.sh

**Comment by jakajancar** [comment]
Ah, that works. Perhaps even better to leave the caller in control. Thanks.
