### ISSUE TITLE
Configurability of block device names

### ISSUE THREAD

**Issue by ecnahc515** [mist64/xhyve#48]
When passing a disk image/file to xhyve using `-s 4,virtio-blk,/path/to/file` it would be nice to be able to specify the name of the device available from within the guest.

For example, I'm mounting in a root disk and I would like to be able to guarantee it's name is `/dev/vda`. I can work around this with labels to an extent, but if I'm building a tool which allows users to pass their own arbitrary disk image, then I can always guarantee the label is properly set. Right now it's all workable, but having a deterministic device name would be quite helpful. Is there anyway to do this currently?

**Comment by AntonioMeireles** [comment]
@ecnahc515 unless i'm missing something (or i had misunderstood yor question) this hasn't anything to do with xhyve (which one would want to be as agnostic as possible regarding abstracted OS). the only thing one needs to assure (for deterministic behaviour inside the VM) is that whatever devices (virtual disks, net interfaces) we pass to it, we always pass them the exact same way (within the same *slot*) which afaict is all one needs in order to get consistent device naming via systemd(udev) these days.

**Comment by ailispaw** [comment]
As @AntonioMeireles mentioned as above, I also think it depends on OS, but regularly `-s 4:0,virtio-blk,/path/to/file` goes to `/dev/vda` and `-s 4:1,virtio-blk,/path/to/file` goes to `/dev/vdb`.

**Comment by xez** [comment]
Yep, xhyve only exposes PCI VirtIO block devices to the guest, it has no control over the device name. One would hope that the guest OS in question enumerates devices deterministically. One layer of abstraction higher one could play around with volume UUIDs to get specific mount points.

**Comment by ecnahc515** [comment]
I see, my depth knowledge here isn't that great, so I appreciate the information. I'll need to look into this more. Thanks.
